#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell available, you may
#       specify it by setting the SHELL variable when running this script.
#       For example: SHELL=/bin/ksh myscript
#
#   (2) The Linux kernel's exec-msg text assumes the script to not contain a
#       newline at the end, so any content following this file may be deleted.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for daisy-chained symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
pw=false
darwin=false
nonstop=false
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/bin/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/bin/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      /*)
        MAX_FD_LIMIT=`expr $MAX_FD : '.*'`
        ;;
      *)
        MAX_FD_LIMIT=$((9223372036854775807))
        ;;
    esac
    ulimit -n $MAX_FD_LIMIT
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...system properties
#   * -U...user properties

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`

    JAVACMD=`cygpath --unix "$JAVACMD"`

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=`cygpath --path --mixed "$arg"`
        fi
        arg=`cygpath --quote-simple "$arg"`
        NEW_ARGS="$NEW_ARGS $arg"
    done
    # add the classpath
    if [ -n "$CLASSPATH" ] ; then
        NEW_ARGS="-classpath $CLASSPATH $NEW_ARGS"
    fi
    # add default JVM options if needed
    if [ -z "$JAVA_OPTS" ] ; then
        JAVA_OPTS=$DEFAULT_JVM_OPTS
    fi
    JAVA_OPTS=`cygpath --quote-simple "$JAVA_OPTS"`
    NEW_ARGS="$NEW_ARGS -Dorg.gradle.appname=$APP_BASE_NAME $JAVA_OPTS"
else
    # add the classpath
    if [ -n "$CLASSPATH" ] ; then
        NEW_ARGS="-classpath $CLASSPATH $NEW_ARGS"
    fi
    # add default JVM options if needed
    if [ -z "$JAVA_OPTS" ] ; then
        JAVA_OPTS=$DEFAULT_JVM_OPTS
    fi
    NEW_ARGS="$NEW_ARGS -Dorg.gradle.appname=$APP_BASE_NAME $JAVA_OPTS"
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#       shell commands/variable substitutions, so put them in double quotes to make
#       sure that they get re-expanded; and
#   * put everything else in single quotes, so that the shell interprets these
#       arguments literally.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" around will consume the last arg and stop when there is no more input left.
# in other words, as long as the current argument string resolves to a non-empty string from the end of the loop.
while :
do
    case $1 in #(
      -*)   false ;;                            # don't mess with options #(
      /?*)  t=${1#/} t=/${t%%/*}              # looks like a POSIX filepath
            [ -e "$t" ] ;;                      #(
      *)    false ;;
    esac
    prophs=$((prophs + 1))
    shift
    case $1 in #(
      -*)   ;;                                # don't mess with options #(
      *)    set -- "$@" "$1"; shift ;;
    esac
done
exec "$JAVACMD" "$@"
