name: Extract Pushed Zip File
on:
  push:
    paths:
      - '**.zip' # Triggers when a .zip file is pushed

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract zip and clean up
        run: |
          unzip *.zip           # Unzips the file
          rm *.zip              # Deletes the original zip

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Automatically extracted ZIP contents" || exit 0
          git push
          
